apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-cicd-app
  template:
    metadata:
      labels:
        app: simple-cicd-app
    spec:
      containers:
      - name: simple-cicd-container
        image: kisakitetta/simple-cicd-app:latest
        ports:
        - containerPort: 3000
