apiVersion: v1
kind: Service
metadata:
  name: simple-cicd-service
spec:
  type: NodePort
  selector:
    app: simple-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080